// Code generated by mockery v2.44.1. DO NOT EDIT.

package nftmonitor

import (
	nl "github.com/wildberries-tech/pkt-tracer/internal/nl"
	
	mock "github.com/stretchr/testify/mock"
)

// MockNetlinkWatcher is an autogenerated mock type for the NetlinkWatcher type
type MockNetlinkWatcher struct {
	mock.Mock
}

// Read provides a mock function with given fields:
func (_m *MockNetlinkWatcher) Read() chan nl.NlData {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 chan nl.NlData
	if rf, ok := ret.Get(0).(func() chan nl.NlData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan nl.NlData)
		}
	}

	return r0
}

// NewMockNetlinkWatcher creates a new instance of MockNetlinkWatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNetlinkWatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNetlinkWatcher {
	mock := &MockNetlinkWatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
