// Code generated by mockery v2.44.1. DO NOT EDIT.

package nftmonitor

import (
	context "context"

	tracehub "github.com/wildberries-tech/pkt-tracer/pkg/api/tracehub"

	mock "github.com/stretchr/testify/mock"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockStreamCli is an autogenerated mock type for the StreamCli type
type MockStreamCli struct {
	mock.Mock
}

// CloseAndRecv provides a mock function with given fields:
func (_m *MockStreamCli) CloseAndRecv() (*emptypb.Empty, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseAndRecv")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func() (*emptypb.Empty, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *emptypb.Empty); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Context provides a mock function with given fields:
func (_m *MockStreamCli) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// Send provides a mock function with given fields: _a0
func (_m *MockStreamCli) Send(_a0 *tracehub.SyncTableReq) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*tracehub.SyncTableReq) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockStreamCli creates a new instance of MockStreamCli. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamCli(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamCli {
	mock := &MockStreamCli{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
